ENTITY_CONCEPT_NAMES = [
    'Anesthesiology Critical Care Medicine', 'Adolescent Medicine', 'Adult Congenital Heart Disease', 'Advanced Heart Failure and Transplant Cardiology', 'Aerospace Medicine',
    
    'Brain Injury Medicine', 'Blood Banking / Transfusion Medicine', 'Borderline', 'benzyl alcohol; topical', 'Birth weight',
    
    'Cytopathology', 'Congenital Cardiac Surgery', 'Complex General Surgical Oncology', 'Clinical Neurophysiology', 'Clinical Molecular Genetics',
    
    'Diagnostic Radiology', 'Developmental-Behavioral Pediatrics', 'Diagnostic Medical Physics', 'Dermatopathology', 'dimeticone; topical',
    
    'Epilepsy', 'Endocrinology, Diabetes and Metabolism', 'Emergency Medical Services', 'ethacridine lactate; irrigating solution', 'etohexadiol; topical',
    
    'Forensic Psychiatry', 'Female Pelvic Medicine and Reconstructive Surgery', 'Female Pelvic Medicine and Reconstructive Surgery', 'fulvestrant 250mg/5mL INTRAMUSCULAR INJECTION', 'Floaters in visual field',
    
    'Geriatric Psychiatry', 'Generally unwell', 'gliclazide; oral', 'glisoxepide; oral', 'glimepiride; oral',
    
    'Hospice and Palliative Medicine', 'hemorrhoidal cream 10mg/g / 144mg/g / 150mg/g / 2.5mg/g TOPICAL CREAM', 'histamine dihydrochloride .0005g/g TOPICAL CREAM', 'Hb. A1C - glycated hemoglobin (& [diabetic control])', 'Hb. A1C - glycated hemoglobin (& [diabetic control])',
    
    'Interventional Cardiology', 'Internal Medicine - Critical Care Medicine', 'INSECTICIDES AND REPELLENTS', 'influenzinum (2022-2023),herpes simplex 1 nosode, herpes simplex 2 nosode, human herpesvirus 6a, hu... 12[hp_C]/mL / 12[hp_X]/mL / 15[hp_X]/mL / 16[hp_C]/mL / 33[hp_X]/mL ORAL LIQUID', 'indometacin; topical',
    
    'josamycin; oral', 'Janus-associated kinase (JAK) inhibitors', 'Jamaican dollar', 'Jordanian dinar', 'Japanese yen',
    
    'kali muriaticum, carbo vegetabilis, lung (suis), mycoplasma pneumoniae, bryonia (alba), gelsemium se... 6[hp_X]/mL / 8[hp_X]/mL / 12[hp_X]/mL / 16[hp_X]/mL / 30[hp_X]/mL ORAL LIQUID', 'ketazolam; oral', 'kanamycin; oral', 'kaolin; oral', 'ketanserin; systemic',
    
    'Laboratory Genetics and Genomics', 'Length of gestation', 'Luteinizing hormone (& serum level)', 'larotrectinib; oral', 'lafutidine; oral', 
    
    'Microbiology', 'Molecular Genetic Pathology', 'Medical Toxicology', 'Medical Physics', 'Medical Genetics and Genomics', 
    
    'Nuclear Radiology', 'Neurotology', 'Neuroradiology', 'Neuropathology', 'Neuromuscular Medicine', 
    
    'Orthopaedic Sports Medicine', 'Other insecticides and repellents', 'O/E - hyperesthesia present (& [hyperalgesia])', 'O/E - senility - no psychosis', 'O/E - micturition reflex NOS', 
    
    'Pediatric Cardiology', 'Pediatric Anesthesiology', 'Pathology-Anatomic / Pathology-Clinical', 'Pathology - Pediatric', 'Pathology - Molecular Genetic', 
    
    'quizartinib; oral', 'quinbolone; systemic', 'quinidine; oral', 'quinidine, combinations excl. psycholeptics; systemic', 'quinidine, combinations with psycholeptics; systemic', 
    
    'Reproductive Endocrinology / Infertility', 'Radiology', 'Refer to health visitor (& referred to)', 'RBC folate borderline', 'RESPIRATORY SYSTEM', 
    
    'Spinal Cord Injury Medicine', 'Surgical Critical Care', 'Sports Medicine', 'Sleep Medicine', 'sulfamethizole; irrigating solution', 
    
    'Therapeutic Medical Physics', 'Thoracic and Cardiac Surgery', 'Transplant Hepatology', 'taurolidine; irrigating solution', 'tetramethrin; topical', 
    
    'Undersea and Hyperbaric Medicine', 'Urgent desire to urinate', 'Unable to think clearly', 'Unformed visual hallucinations', 'umifenovir; oral', 
    
    'Vascular Neurology', 'Vascular and Interventional Radiology', 'varenicline 1mg/1 ORAL TABLET, FILM COATED', 'Visual symptom NOS', 'viloxazine; oral', 
    
    'Whole blood folate borderline', 'Well child', 'Worried well', 'warfarin; systemic', 'Wart and anti-corn preparations', 
    
    'ximelagatran; oral', 'xamoterol; oral', 'xipamide; oral', 'Xanthine derivatives', 'xantinol nicotinate; systemic', 
    
    'yohimbine; oral', 'Yellow fever vaccines', 'yellow fever, live attenuated; systemic', 'Yttrium (90Y) compounds', 'yttrium (90Y) citrate colloid', 
    
    'Zinc', 'zolpidem; oral', 'zaleplon; oral', 'zolimidine', 'zinc sulfate; oral'
]

RELATIONSHIP_NAMES = [
    'Has specimen procedure',
    'Has specimen source identity',
    'Has specimen source morphology',
    'Has specimen source topography',
    'Has specimen substance',
    'Has due to',
    'Has subject relationship context',
    'Has dose form',
    'Occurs after',
    'Has associated procedure',
    'Has direct procedure site',
    'Has indirect procedure site',
    'Has procedure device',
    'Has procedure morphology',
    'Has finding context',
    'Has procedure context',
    'Has temporal context',
    'Associated with finding',
    'Has surgical approach',
    'Using device',
    'Using energy',
    'Using substance',
    'Using access device',
    'Has clinical course',
    'Has route of administration',
    'Using finding method',
    'Using finding informer',
    'ICD-9-Procedure to SNOMED equivalent',
    'CPT-4 to SNOMED equivalent',
    'MedDRA to SNOMED equivalent',
    'Has FDA-approved drug indication',
    'Has off-label drug indication',
    'Has drug contra-indication',
    'ETC to RxNorm',
    'SMQ consists of MedDRA',
    'Concept replaces',
    'Precise ingredient of',
    'Tradename of',
    'Dose form of',
    'Form of',
    'Ingredient of',
    'Consists of',
    'Is contained in',
    'Reformulated in',
    'Dose form of',
    'Induced by',
    'Diagnosed through',
    'Physiological effect induced by',
    'Contraindicating physiological effect induced by',
    'Ingredient of',
    'Contraindicating chemical class of',
    'Mechanism of action of',
    'Contraindicating mechanism of action of',
    'Pharmacokinetics of',
    'May be treated by',
    'Contraindicated by',
    'May be prevented by',
    'Active metabolite of',
    'Site of metabolism of',
    'Inhibits effect',
    'Chemical structure of',
    'RxNorm to NDF-RT equivalent',
    'Recipient category of',
    'Procedure site of',
    'Priority of',
    'Pathological process of',
    'Part of',
    'Severity of',
    'Revision status of',
    'Access of',
    'Occurrence of',
    'Laterality of',
    'Interprets of',
    'Indirect morphology of',
    'ATC to RxNorm',
    'Is a',
    'CPT-4 to SNOMED category',
    'Indirect device of',
    'Specimen of',
    'Interpretation of',
    'Intent of',
    'Focus of',
    'Definitional manifestation of',
    'Active ingredient of',
    'Finding site of',
    'Episodicity of',
    'Direct substance of',
    'Direct morphology of',
    'Direct device of',
    'Causative agent of',
    'Associated morphology of',
    'Associated finding of',
    'Measurement method of',
    'Specimen procedure of',
    'Specimen source identity of',
    'Specimen source morphology of',
    'Specimen source topography of',
    'Specimen substance of',
    'Due to of',
    'Subject relationship context of',
    'Dose form of',
    'Occurs before',
    'Associated procedure of',
    'Direct procedure site of',
    'Indirect procedure site of',
    'Procedure device of',
    'Procedure morphology of',
    'Finding context of',
    'Procedure context of',
    'Temporal context of',
    'Finding associated with',
    'Surgical approach of',
    'Device used by',
    'Energy used by',
    'Substance used by',
    'Access device used by',
    'Has clinical course of',
    'Route of administration of',
    'Finding method of',
    'Finding informer of',
    'SNOMED to ICD-9-Procedure equivalent',
    'SNOMED category to CPT-4',
    'SNOMED to CPT-4 equivalent',
    'SNOMED to MedDRA equivalent',
    'Is FDA-approved indication of',
    'Is off-label indication of',
    'Is contra-indication of',
    'RxNorm to ETC',
    'RxNorm to ATC',
    'MedDRA contained in SMQ',
    'Has inferred drug class',
    'SNOMED procedure subsumes HCPCS',
    'HCPCS is a SNOMED procedure',
    'RxNorm to NDF-RT equivalent by concept_name',
    'NDF-RT to RxNorm equivalent by concept_name',
    'ETC to RxNorm equivalent by concept_name',
    'RxNorm to ETC equivalent by concept_name',
    'RxNorm to ATC equivalent by concept_name',
    'HOI contains SNOMED',
    'SNOMED contained in HOI',
    'DOI contains RxNorm',
    'RxNorm contained in DOI',
    'HOI contains MedDRA',
    'MedDRA contained in HOI',
    'NUCC to CMS Specialty',
    'CMS Specialty to NUCC',
    'DRG to MS-DRG equivalent',
    'MS-DRG to DRG equivalent',
    'DRG to MDC category',
    'Component of',
    'Scale type of',
    'Property of',
    'ATC to RxNorm equivalent by concept_name',
    'MDC category to DRG',
    'Visit category to Place of Service',
    'Place of Service to Visit category',
    'VA Product to NDF-RT',
    'NDF-RT to VA Product',
    'VA Product to RxNorm equivalent',
    'RxNorm to VA Product equivalent',
    'Concept replaced by',
    'Concept replaces',
    'Has ingredient',
    'Ingredient of',
    'RxNorm to Drug Source equivalent',
    'Drug Source to RxNorm equivalent',
    'Concept replaced by',
    'Concept replaces',
    'Inactive same_as active',
    'Active same_as inactive',
    'Inactive alternative_to active',
    'Active alternative_to inactive',
    'Inactive possibly_equivalent_to active',
    'Active possibly_equivalent_to inactive',
    'Inactive was_a active',
    'Active was_a inactive',
    'SNOMED measurement subsumes HCPCS',
    'HCPCS is a SNOMED measurement',
    'Domain subsumes',
    'Is a domain',
    'Standard to Non-standard exclude child',
    'Concept replaced by',
    'Concept replaces',
    'Module of',
    'Standard to Non-standard include child',
    'Non-standard to Standard exclude child',
    'Non-standard to Standard include child',
    'Standard to Non-standard map',
    'Non-standard to Standard map',
    'Concept replaced by',
    'Concept replaces',
    'Non-standard to type concept map',
    'Non-standard to unit concept map',
    'Non-standard to value_as_concept map',
    'Type concept to non-standard map',
    'Unit concept to non-standard map',
    'Value_as_concept to non-standard map',
    'ICD-9-CM to MedDRA',
    'MedDRA to ICD-9-CM',
    'ICD-9-CM to FDB Indication/Contraindication',
    'FDB Indication/Contraindication to ICD-9-CM',
    'Has Extent',
    'Extent of',
    'Has Approach',
    'Indication/Contra-indication to SNOMED',
    'SNOMED to Indication/Contra-indication',
    'Has therapeutic class',
    'Therapeutic class of',
    'Drug-drug interaction for',
    'Is involved in drug-drug interaction',
    'Has pharmaceutical preparation',
    'Pharmaceutical preparation contained in',
    'Inferred drug class of',
    'Approach of',
    'Has quantified form',
    'Has dispensed dose form',
    'Dispensed dose form of',
    'Has specific active ingredient',
    'Specific active ingredient of',
    'Has basis of strength substance',
    'Basis of strength substance of',
    'Has Virtual Medicinal Product',
    'Virtual Medicinal Product of',
    'Has incipient',
    'Has Answer',
    'Answer of',
    'Incipient of',
    'Has licensed route',
    'Licensed route of',
    'Has unit relating to the size',
    'Unit relating to the size of',
    'Has unit relating to the entity that can be handled',
    'Unit relating to the entity that can be handled of',
    'Has route',
    'Route of',
    'Has Actual Medicinal Product',
    'Actual Medicinal Product of',
    'Is pack of',
    'Has pack',
    'Has trade family group',
    'Trade family group of',
    'Has excipient',
    'Excipient of',
    'Follows',
    'Followed by',
    'Has VMP non-availability indicator',
    'VMP non-availability indicator of',
    'Has ARP',
    'ARP of',
    'Has VRP',
    'VRP of',
    'Has flavor',
    'Flavor of',
    'Has discontinued indicator',
    'Discontinued indicator of',
    'VRP has prescribing status',
    'VRP prescribing status of',
    'Has legal category',
    'Legal category of',
    'LOINC Hierarchy to SNOMED equivalent',
    'SNOMED to LOINC Hierarchy equivalent',
    'LOINC to CPT4 equivalent',
    'CPT4 to LOINC equivalent',
    'OPCS4 to SNOMED equivalent or categorical',
    'SNOMED to OPCS4 equivalent or categorical',
    'Has brand name',
    'Brand name of',
    'Is available in a prepackaged box',
    'Prepackaged box of',
    'Is standard ingredient of ingredient',
    'Has standard ingredient',
    'Is standard Brand Name of',
    'Has standard Brand Name',
    'Is standard Dose Form of',
    'Has standard Dose Form',
    'Drug has drug class',
    'Has marketed form',
    'Marketed form of',
    'Has supplier or manufacturer',
    'Supplier or manufacturer of',
    'Dose form group of',
    'Has dose form group',
    'Has precondition',
    'Precondition of',
    'Has inherent location',
    'Inherent location of',
    'Has technique',
    'Technique of',
    'Has relative part',
    'Relative part of',
    'Has process output',
    'Process output of',
    'Inheres in',
    'Has inherent',
    'Has direct site',
    'Direct site of',
    'Characterizes',
    'VMP prescribing status of',
    'Has property type',
    'Property type of',
    'Drug class of drug',
    'Panel contains',
    'Contained in panel',
    'Is characterized by',
    'RxNorm - CVX',
    'CVX - RxNorm',
    'Has Module',
    'Presentation strength denominator unit of',
    'Has presentation strength denominator value',
    'Topic of',
    'Has Topic',
    'Has presentation strength denominator unit',
    'Presentation strength denominator value of',
    'Has presentation strength numerator unit',
    'Presentation strength numerator unit of',
    'Has presentation strength numerator value',
    'Presentation strength numerator value of',
    'During',
    'Has complication',
    'Has Histology ICDO',
    'Histology of ICDO',
    'Has Topography ICDO',
    'Topography of ICDO',
    'ICDO - SNOMED',
    'SNOMED - ICDO',
    'Has basic dose form',
    'Basic dose form of',
    'Has disposition',
    'Disposition of',
    'Has dose form administration method',
    'Dose form administration method of',
    'Has dose form intended site',
    'Dose form intended site of',
    'Has dose form release characteristic',
    'Dose form release characteristic of',
    'Has dose form transformation',
    'Dose form transformation of',
    'Has state of matter',
    'State of matter of',
    'Temporally related to',
    'Has temporal finding',
    'Typ bill Full to Frequency code',
    'Frequency code to Typ bill Full',
    'Typ bill Full to Typ bill 3 digits',
    'Typ bill 3 digits to Typ bill Full',
    'Has Morphology',
    'Morphology of',
    'Has Measured Component',
    'Measured Component of',
    'Caused by',
    'Causes',
    'Has Etiology',
    'Etiology of',
    'Has Stage',
    'Stage of',
    'Quantified form of',
    'Is a',
    'Inverse is a',
    'VA Class to ATC equivalent',
    'ATC to VA Class equivalent',
    'NDFRT to ATC equivalent',
    'ATC to NDFRT equivalent',
    'VA Class to NDFRT equivalent',
    'NDFRT to VA Class equivalent',
    'Chemical Structure to Pharmaceutical Preparation equivalent',
    'Pharmaceutical Preparation to Chemical Structure equivalent',
    'SNOMED to RxNorm equivalent',
    'RxNorm to SNOMED equivalent',
    'SNOMED to NDF-RT equivalent',
    'NDF-RT to SNOMED equivalent',
    'SNOMED to VA Class equivalent',
    'VA Class to SNOMED equivalent',
    'SNOMED to ATC equivalent',
    'ATC to SNOMED equivalent',
    'Has product component',
    'Product component of',
    'SPL to RxNorm',
    'RxNorm to SPL',
    'Non-standard to operator concept map',
    'Operator concept to non-standard map',
    'Non-standard to value_as_number map',
    'Value_as_number to non-standard map',
    'Concept replaced by',
    'Has precise ingredient',
    'Has tradename',
    'Has dose form',
    'Has form',
    'Has ingredient',
    'Constitutes',
    'Contains',
    'Reformulation of',
    'Subsumes',
    'Has dose form',
    'Induces',
    'May diagnose',
    'Has physiological effect',
    'Has contraindicating physiological effect',
    'Has ingredient',
    'Has contraindicating chemical class',
    'Has mechanism of action',
    'Has contraindicating mechanism of action',
    'Has pharmacokinetics',
    'May treat',
    'Contraindication to',
    'May prevent',
    'Has active metabolites',
    'Has site of metabolism',
    'Effect may be inhibited by',
    'Has chemical structure',
    'NDF-RT to RxNorm equivalent',
    'Has recipient category',
    'Has procedure site',
    'Has priority',
    'Has pathological process',
    'Has part of',
    'Has severity',
    'Has revision status',
    'Has access',
    'Has occurrence',
    'Has laterality',
    'Has interprets',
    'Has indirect morphology',
    'Has indirect device',
    'Has specimen',
    'Has interpretation',
    'Has intent',
    'Has focus',
    'Has definitional manifestation',
    'Has active ingredient',
    'Has finding site',
    'Has episodicity',
    'Has direct substance',
    'Has direct morphology',
    'Has direct device',
    'Has causative agent',
    'Has associated morphology',
    'Has associated finding',
    'Has measurement method',
    'Has unit of administration',
    'Unit of administration of',
    'VMP has prescribing status',
    'Has precise active ingredient',
    'Precise active ingredient of',
    'Has unit of presentation',
    'Unit of presentation of',
    'Has concentration strength numerator value',
    'Concentration strength numerator value of',
    'Has concentration strength denominator value',
    'Concentration strength denominator value of',
    'Has concentration strength denominator unit',
    'Concentration strength denominator unit of',
    'Has concentration strength numerator unit',
    'Has scale type',
    'Has property',
    'Concentration strength numerator unit of',
    'Is modification of',
    'Has modification of',
    'Has count of base of active ingredient',
    'Count of base of active ingredient of',
    'Answer of',
    'Has answer',
    'Has subject matter domain',
    'Subject matter domain of',
    'Has type of service',
    'Type of service of',
    'Has role',
    'Role of',
    'Has kind',
    'Kind of',
    'Has setting',
    'Setting of',
    'Has PPI parent code',
    'PPI parent code of',
    'OMOP CDM Version contains table/field',
    'Table/field contained in OMOP CDM Version',
    'Plays role',
    'Role played by',
    'Has physiologic state',
    'Physiologic state of',
    'Includes sub-specimen',
    'Sub-specimen of',
    'Has life circumstance',
    'Life circumstance',
    'Has vaccine group',
    'Vaccine group of',
    'Has antineoplastic - RxNorm',
    'RxNorm antineoplastic of',
    'Has antineoplastic',
    'Antineoplastic of',
    'Has context',
    'Context of',
    'Has immunosuppressor - RxNorm',
    'RxNorm immunosuppressor of',
    'Has immunosuppressor',
    'Immunosuppressor of',
    'Has local therapy - RxNorm',
    'RxNorm local therapy of',
    'Has local therapy',
    'Local therapy of',
    'Has regimen type',
    'Regimen type of',
    'Has supportive medication',
    'Supportive medication of',
    'May have route',
    'May be route of',
    'Has permissible range',
    'CPT4 to CVX equivalent',
    'CVX to CPT4 equivalent',
    'Procedure Schema to ICDO Condition',
    'ICDO Condition to Procedure Schema',
    'Schema to ICDO Condition',
    'ICDO Condition to Schema',
    'Schema to Value',
    'Value to Schema',
    'Schema to Variable',
    'Variable to Schema',
    'Has parent item',
    'Parent item of',
    'Variable has date',
    'Date of variable',
    'Permissible range of',
    'Has unit',
    'Unit of',
    'Has type',
    'Type of',
    'Has controlled drug category',
    'Controlled drug cathehory of',
    'Has ontological dose form presentation',
    'Ontological dose form presentation of',
    'Has combination product indicator',
    'RxNorm Supportive medication of',
    'Combination product indicator of',
    'Has dose form continuity indicator',
    'Dose form continuity indicator',
    'Has modality',
    'Modality of',
    'Has method',
    'Method of',
    'Has time aspect',
    'Time aspect of',
    'Has component',
    'Has end date',
    'End date of',
    'Has start date',
    'Start date of',
    'Has system',
    'System of',
    'Has NHS dm+d (dictionary of medicines and devices) additional monitoring indicator',
    'NHS dm+d (dictionary of medicines and devices) additional monitoring indicator of',
    'Has NHS dm+d (dictionary of medicines and devices) AMP (actual medicinal product) availability restriction indicator',
    'NHS dm+d (dictionary of medicines and devices) AMP (actual medicinal product) availability restriction indicator of',
    'Has NHS dm+d parallel import indicator',
    'NHS dm+d parallel import indicator of',
    'Has NHS dm+d freeness indicator',
    'NHS dm+d freenes indicator of',
    'Process duration',
    'Process duration of',
    'CAP value of',
    'Has CAP value',
    'Has CAP parent item',
    'CAP parent item of',
    'Has CAP protocol',
    'CAP protocol of',
    'CAP to Nebraska Lexicon category',
    'Nebraska Lexicon to CAP category',
    'CAP to Nebraska Lexicon equivalent',
    'Nebraska Lexicon to CAP equivalent',
    'Has accepted use',
    'Accepted use of',
    'Has FDA indication',
    'FDA indication of',
    'Is currently used in',
    'Currently treated by',
    'Is historically used in',
    'Historically treated by',
    'ATC to RxNorm/Extension primary lateral',
    'RxNorm/Extension to ATC pr lateral',
    'ATC to RxNorm/Extension secondary lateral',
    'RxNorm/Extension to ATC secondary lateral',
    'ATC to RxNorm/Extension primary upwards',
    'RxNorm/Extension to ATC primary upwards',
    'ATC to RxNorm/Extension secondary upwards',
    'RxNorm/Extension to ATC secondary upwards',
    'Has question source',
    'Question source of',
    'Has Value',
    'Value of',
    'Category in Chapter',
    'Chapter has Category',
    'Chapter to ICDO',
    'ICDO to Chapter',
    'Has precoordinated (Question-Answer/Variable-Value) pair',
    'Precoordinated (Question-Answer/Variable-Value) pair of',
    'Has Category',
    'Category of',
    'Has biosimilar',
    'Biosimilar of',
    'Relative to',
    'Relative to of',
    'Count of active ingredients',
    'Is count of active ingredients in',
    'Has product characteristic',
    'Product characteristic of',
    'Has surface characteristic',
    'Surface characteristic of',
    'Has device intended site',
    'Device intended site of',
    'Has compositional material',
    'Compositional material of',
    'Has filling',
    'Filling material of',
    'Reference to variant',
    'Variant refer to concept',
    'Genomic DNA transcribes to mRNA',
    'mRNA Translates to protein',
    'mRNA is transcribed from genomic DNA',
    'Protein is translated from mRNA',
    'OncoTree to ICDO equivalent',
    'ICDO to OncoTree equivalent',
    'OncoTree to ICDO broader',
    'ICDO broader to OncoTree',
    'Has antibody-drug conjugate',
    'Antibody-drug conjugate of',
    'Has antibody-drug conjugate - RxNorm',
    'Has FDA labeling',
    'FDA labeling of',
    'Has cytotoxic chemotherapy',
    'Cytotoxic chemotherapy of',
    'Has cytotoxic chemotherapy - RxNorm',
    'Cytotoxic chemotherapy of - RxNorm',
    'Has endocrine therapy',
    'Endocrine therapy of',
    'Has endocrine therapy - RxNorm',
    'Has immunotherapy',
    'Immunotherapy of',
    'Has immunotherapy - RxNorm',
    'Has peptide-drug conjugate',
    'Peptide-drug conjugate of',
    'Has peptide-drug conjugate - RxNorm',
    'Has radioconjugate',
    'Radioconjugate of',
    'Has radioconjugate - RxNorm',
    'Has radiotherapy',
    'Radiotherapy of',
    'Has radiotherapy - RxNorm',
    'Has targeted therapy',
    'Targeted therapy of',
    'Has targeted therapy - RxNorm',
    'Has supportive medication - RxNorm',
    'Has coating material',
    'Coating material of',
    'Has absorbability',
    'Absorbability of',
    'Process extends to',
    'Process extends from',
    'Has ingredient qualitative strength',
    'RxNorm antibody-drug conjugate of',
    'RxNorm endocrine therapy of',
    'RxNorm immunotherapy of',
    'RxNorm peptide-drug conjugate of',
    'RxNorm radioconjugate of',
    'RxNorm radiotherapy of',
    'RxNorm targeted therapy of',
    'Ingredient qualitative strength of',
    'Has surface texture',
    'Surface texture of',
    'Is sterile',
    'Is sterile of',
    'Has target population',
    'Target population of',
    'Has status',
    'Status of',
    'Has steroid therapy',
    'Steroid therapy of',
    'Has steroid therapy - RxNorm',
    'RxNorm steroid therapy of',
    'Is current in adult',
    'Current adult indication for',
    'Is current in pediatric',
    'Current pediatric indication for',
    'Is historical in adult',
    'Historical adult indication for',
    'Had accepted use',
    'Had accepted for',
    'Has investigational use',
    'Investigational use for',
    'Has PDC - RxNorm',
    'RxNorm PDC of',
    'Is historical in pediatric',
    'Historical pediatric indication for',
    'Process acts on',
    'Affected by process',
    'Before',
    'After',
    'Towards',
    'Subject of']